# Generated by Django 3.2.8 on 2021-10-31 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Human_orm',
            new_name='Human',
        ),
    ]
