# Generated by Django 3.2.8 on 2021-10-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer', models.IntegerField(default=100)),
                ('pos_integer', models.PositiveIntegerField()),
                ('float_field', models.FloatField()),
                ('boolean_field', models.BooleanField()),
                ('char_field', models.CharField(max_length=20)),
                ('email_field', models.EmailField(blank=True, max_length=254, null=True)),
                ('file_field', models.FileField(blank=True, null=True, upload_to='file')),
                ('images_field', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
